import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar"
import Footer from "./components/Footer";
import TestimonialSlider from "./components/TestimonialSlider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className='kuchnhi'
      >
        <Navbar/>
        <main>

        {children}
        </main>
        <TestimonialSlider/>
       <Footer/>
      </body>
    </html>
  );
}
